export const langs = [
  { code: "en", name: "English" },
  { code: "de", name: "Deutsch" },
  { code: "fr", name: "Français" },
  { code: "ru", name: "Русский" },
  { code: "it", name: "Italiano" },
  { code: "es", name: "Español" },
  { code: "pl", name: "Polski" },
  { code: "ja", name: "日本語" },
  { code: "zh", name: "中文" },
  { code: "pt", name: "Português" },
  { code: "no", name: "Norsk bokmål" },
  { code: "nn", name: "Norsk nynorsk" },
  { code: "ar", name: "العربية" },
  { code: "nl", name: "Nederlands" },
  { code: "ceb", name: "Sinugboanong Binisaya" },
  { code: "sv", name: "Svenska" },
  { code: "vi", name: "Tiếng Việt" },
  { code: "war", name: "Winaray" },
];
