export const langs = [
  { code: "en", name: "English", wp: "Wikipedia" },
  { code: "de", name: "Deutsch", wp: "Wikipedia" },
  { code: "fr", name: "Français", wp: "Wikipédia" },
  { code: "ru", name: "Русский", wp: "Википедия" },
  { code: "it", name: "Italiano", wp: "Wikipedia" },
  { code: "es", name: "Español", wp: "Wikipedia" },
  { code: "pl", name: "Polski", wp: "Wikipedia" },
  { code: "ja", name: "日本語", wp: "ウィキペディア" },
  { code: "zh", name: "中文", wp: "维基百科" },
  { code: "pt", name: "Português", wp: "Wikipédia" },
  { code: "no", name: "Norsk bokmål", wp: "Wikipedia" },
  { code: "nn", name: "Norsk nynorsk", wp: "Wikipedia" },
  { code: "ar", name: "العربية", wp: "ويكيبيديا" },
  { code: "nl", name: "Nederlands", wp: "Wikipedia" },
  { code: "ceb", name: "Sinugboanong Binisaya", wp: "Wikipedya" },
  { code: "sv", name: "Svenska", wp: "Wikipedia" },
  { code: "vi", name: "Tiếng Việt", wp: "Wikipedia" },
  { code: "war", name: "Winaray", wp: "Wikipedia" },
];
